name: Validate Gradle Wrapper
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  validation:
    name: Validation
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
