# GitHub Actions to skip build execution based on commit message
# If the commit message (or a merge message) contains [ci skip] (in subject of body) the action will stop.

name: Skip build execution based on commit message

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '.*'

jobs:
  CI_SKIP_JOB:
    runs-on: ubuntu-latest
    name: Should success
    steps:
      - uses: actions/checkout@v2
        with:
          # Contains [ci skip] in message body
          fetch-depth: '0'
      - uses: mstachniuk/ci-skip@master
      - name: Check env
        run: |
          echo "CI_SKIP is $CI_SKIP"
          echo "CI_SKIP_NOT is $CI_SKIP_NOT"
          if [[ "$CI_SKIP" != true ]]; then
            echo "The CI_SKIP env should be set to true, but it is: $CI_SKIP"
            exit 1
          fi
          if [[ "$CI_SKIP_NOT" != false ]]; then
            echo "The CI_SKIP_NOT env should be set to false, but it is: $CI_SKIP_NOT"
            exit 2
          fi
      - name: Check if expression CI_SKIP
        if: ${{ env.CI_SKIP == 'false' }}
        run: |
          echo "This step should not be executed"
          echo "CI_SKIP is $CI_SKIP"
          exit 3
      - name: Check if expression CI_SKIP_NOT
        if: ${{ env.CI_SKIP_NOT == 'true' }}
        run: |
          echo "This step should not be executed"
          echo "CI_SKIP_NOT is $CI_SKIP_NOT"
          exit 4